language: java
sudo: false
jdk:
- oraclejdk8
env:
- DISPLAY=:99.0
before_install:
- chmod +x ./gradlew
- chmod +x ./BuildDevint
- sh -e /etc/init.d/xvfb start
script:
- touch PluginsAndFeatures/AddLibrary/JDBCLibrary/JavaEE6/com.microsoft.sqljdbc4/sqljdbc42.jar
- ./BuildDevint -q
