language: java
sudo: false
jdk:
- oraclejdk8
before_install:
 - chmod +x ./gradlew
script:
- mvn install -f Utils/azuretools-core/pom.xml -q
- mvn install -f Utils/azure-explorer-common/pom.xml -q
- mvn install -f Utils/hdinsight-node-common/pom.xml -q
- ./gradlew -v
- ./gradlew buildPlugin -Pintellij_version=IU-2016.3 -Pdep_plugins=org.intellij.scala:2016.3.5 --project-dir PluginsAndFeatures/azure-toolkit-for-intellij  -s
- ./gradlew buildPlugin --project-dir PluginsAndFeatures/azure-toolkit-for-intellij -s