/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.hdinsight.sdk.rest.sparkserverless.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Spark specific resource pool information.
 */
public class SparkResourcePoolProperties {
    /**
     * Name for the spark resource pool.
     */
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /**
     * Version of the template used while deploying the resource pool.
     */
    @JsonProperty(value = "resourcePoolVersion", access = JsonProperty.Access.WRITE_ONLY)
    private String resourcePoolVersion;

    /**
     * Spark version to be deployed on the instances of the resource pool.
     */
    @JsonProperty(value = "sparkVersion", access = JsonProperty.Access.WRITE_ONLY)
    private String sparkVersion;

    /**
     * Account name of the storage account (ADLS) where logs and history will
     * be stored.
     */
    @JsonProperty(value = "userStorageAccount", access = JsonProperty.Access.WRITE_ONLY)
    private String userStorageAccount;

    /**
     * Definition of spark master and spark workers.
     */
    @JsonProperty(value = "sparkResourceCollection", access = JsonProperty.Access.WRITE_ONLY)
    private List<SparkResourcePoolItemProperties> sparkResourceCollection;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Get the resourcePoolVersion value.
     *
     * @return the resourcePoolVersion value
     */
    public String resourcePoolVersion() {
        return this.resourcePoolVersion;
    }

    /**
     * Get the sparkVersion value.
     *
     * @return the sparkVersion value
     */
    public String sparkVersion() {
        return this.sparkVersion;
    }

    /**
     * Get the userStorageAccount value.
     *
     * @return the userStorageAccount value
     */
    public String userStorageAccount() {
        return this.userStorageAccount;
    }

    /**
     * Get the sparkResourceCollection value.
     *
     * @return the sparkResourceCollection value
     */
    public List<SparkResourcePoolItemProperties> sparkResourceCollection() {
        return this.sparkResourceCollection;
    }

}
