name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/develop
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Windows_2022
      os: windows
    sdl:
      # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview
      spotBugs:
        enabled: false
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-10780-Tool
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            timeoutInMinutes: 0
            displayName: Build and Sign Azure Plugin for IntelliJ
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(build.artifactstagingdirectory)
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                fetchTags: false
              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled
              - task: Bash@3
                displayName: Build Utils
                inputs:
                  targetType: inline
                  script: |-
                    mvn -v
                    git fetch origin $(BRANCH) 
                    git checkout $(BRANCH)
                    # ./gradlew buildUtils || exit -1
                    mvn clean install -f ./Utils/pom.xml -T 1C -Dcheckstyle.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
                    mvn clean -f ./Utils/pom.xml
              - task: Bash@3
                displayName: Build Plugin
                inputs:
                  targetType: inline
                  script: |-
                    mkdir -p ./out/
                    cd PluginsAndFeatures/azure-toolkit-for-intellij
                    ./gradlew clean buildPlugin -s -Papplicationinsights.key=$(INTELLIJ_KEY) -PneedPatchVersion=false -Psources=false -Porg.gradle.configureondemand=false -Porg.gradle.daemon=false -Porg.gradle.unsafe.configuration-cache=false -Porg.gradle.caching=false
                    cp ./build/distributions/*.zip ../../out/azure-toolkit-for-intellij.zip
              ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
              - task: APIScan@2
                displayName: Run APIScan
                inputs:
                  softwareFolder: $(system.defaultworkingdirectory)/out
                  softwareName: 'microsoft.azure-intellij-plugin.sign-stable'
                  softwareVersionNum: '$(Build.BuildId)'
                  isLargeApp: false
                  toolVersion: 'Latest'
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
                env:
                  AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
              - task: CopyFiles@2
                displayName: "Copy Files to: $(build.artifactstagingdirectory)"
                inputs:
                  SourceFolder: $(system.defaultworkingdirectory)/out
                  Contents: "**/*.zip"
                  TargetFolder: $(build.artifactstagingdirectory)
